name: modern_charts
version: 0.1.12
author: Man Hoang <jolleekin@outlook.com>
description: A package for creating simple yet modern looking charts.
homepage: https://github.com/jolleekin/modern_charts
documentation: https://github.com/jolleekin/modern_charts/wiki/Docs
environment:
  sdk: '>=2.0.0-dev.65.0 <3.0.0'
dependencies:
  intl: ^0.15.7